
### Get complete list
GET http://localhost:3000/players?sortCol=name&sortOrder


### Get playerwith specific id
GET http://localhost:3000/players/9


### Create new player
POST http://localhost:3000/players 
Content-Type: application/json; charset=utf-8

{
    "name": "test",
    "jersey": "0",
    "position": "test"
}

### Edit player with id 2
PUT   http://localhost:3000/players/20
Content-Type: application/json; charset=utf-8

{
    "name": "test",
    "jersey": "00",
    "position": "test"
    
}

###Delete player with id 2
DELETE http://localhost:3000/players/23

