
### Get complete list
GET http://localhost:3000/players


### Get playerwith specific id
GET http://localhost:3000/players/9


### Create new player
POST http://localhost:3000/players 
Content-Type: application/json; charset=utf-8

{
    "name": "Peter Forsberg",
    "jersey": "21",
    "position": "Center"
}

### Edit player with id 2
PUT   http://localhost:3000/players/2
Content-Type: application/json; charset=utf-8

{
    "name": "Peter Forsberg",
    "jersey": "21",
    "position": "Center/Forward"
    
}

###Delete player with id 2
DELETE http://localhost:3000/players/2

